apiVersion: v1
kind: Service 
metadata:
  name: usermgmt-webapp-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: usermgmt-webapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008